### ISSUE TITLE
Support simple file-backed CA

### ISSUE THREAD

**Issue by nsmith5** [sigstore/fulcio#276]
**Description**

Some operators may wish to use a simple file based CA to issue certificates. Lets support loading CA signing key and certificate chain from a local files.

Design aspects:
- Will require private key to be encrypted with password
- Cert and private key will be in seperate files
- Cert and private key must be PEM encoded

**Work items**
This work will be broken up into a couple small deliverables below

- [ ] Support a root CA certificate (no certificates chains / intermediates)
- [ ] Add support for intermediate CA / certificate chains
- [ ] Replace `emphemeralca` in the e2e tests for cosign
- [ ] Add documentation of usage (explain the CLI flags / basic example of generating a key-pair with `openssl`)

**Comment by vaikas** [comment]
Yeah, that is what we had tossed around. I also do wonder if this may be of use with some of the load testing that was discussed during the meeting today.

**Comment by nsmith5** [comment]
If I'm reading the google private CA docs right here they can issue intermediate certs https://cloud.google.com/certificate-authority-service/docs/certificate-template (wasn't sure if they did this). Is the idea here that we'd have that cronjob reach up stream to googleca at X frequency to grab a new intermediate make it available (via mounted secret or something) to Fulcio and Fulcio is always signing with the intermediate so that issuing the actual code signing certs is pretty cheap? Basically the cost becomes 0.03$ * the intermediate renewal period

**Comment by mattmoor** [comment]
For all my bits about `googleca` in the CronJob, what I really mean is *any of the real CAs*, that is just my exemplar for a real thing.

**Comment by nsmith5** [comment]
I like the idea, but it does add a bit of operational complexity. I wonder if there is perhaps a way to make this work out of the box instead of needing a cronjob. The cronjobs + kubernetes secret is a fast path to coordination + storage it would be cool if there was another pathway that offered the same value without depending on Kubernetes platform explicitly?

**Comment by nsmith5** [comment]
I suppose the operational overhead is only really a there if folks need this functionality, but if you're running Fulcio yourself you're probably linking it up to an internal PKI and this need to use this functionality falls away pretty quickly

**Comment by mattmoor** [comment]
@nsmith5 What I had in mind was really just an extension of what we have.  Fulcio itself would still support the CA's directly, but we'd add a new one for `fileca` or something.

One way of using `fileca` would be to compose it with a CronJob (we can release) that can consume the same set of CA's asynchronously.

Hopefully that gives folks good choices.  I was not thinking we would require the decoupling.

**Comment by nsmith5** [comment]
Oh yes yes yes. This all makes sense now. If we want the fance Cronjob + secret update to actually work we'd want to make our `fileca` implementation to use something like fsnotify to listen for this file changes on disk and reload the new intermediate right?

**Comment by mattmoor** [comment]
It could even do something much dumber where it just reads it once a minute.  Even per-request might be a fine starting point.

**Comment by vaikas** [comment]
But yeah if @nsmith5 wants to go for ninja credit with fsnotify, that would be awesomesauce :)

**Comment by haydentherapper** [comment]
+1 to the comments about choice. Just chiming in about production - For a production instance, I'd prefer that we exclusively use CA Service.

1) A CA as a service will be more battle-tested than one we've written ourselves.
2) An in-memory signing key is more likely to get leaked or compromised than one hosted on Cloud KMS/Cloud HSM, which is what CA Service uses for signing certificates.
3) Cost goes down a lot as certificate issuance picks up (https://cloud.google.com/certificate-authority-service/pricing). If those running the production instance are fine with the cost, I don't see much value in optimizing for this.

**Comment by mattmoor** [comment]
> If those running the production instance are fine with the cost

My expectation is that over time many folks will operate their own production instance, so this is more about choice than prescribing what we choose to use for the *public good* instance.  We should perhaps have that conversation in a separate issue.

Part of the desire for choice is that while I acknowledge your concerns, I expressed a number of my own with an approach that directly accesses the CA service.  Not everyone will choose the trade-offs you are, and my bigger concerns aren't really about cost.  What is our recourse for handling more than 100 QPS or offering more than a [3 9s SLA](https://cloud.google.com/certificate-authority-service/sla)?

**Comment by dlorenc** [comment]
I hadn't really thought through the options too much, but in my head I was imagining a sort of hybrid architecture for production where the root CA cert is in GCP CA service, but then we have shorter-lived intermediates that are actually used for issuance in the API. These could be stood up at fulcio start time, let's encrypt certbot style, in memory, and rotated at restart or daily.

That would get us better reliability (no RPCs aside from the daily rotations), lower cost (free), and more control over the certs themselves. @asraa has debugged a bunch of issues with the GCP CA service not respecting certain fields in the CSR.

**Comment by mattmoor** [comment]
There is also support for a CSI volume backed by a KMS system, which would provide a much better medium for the intermediates than a K8s Secret.

**Comment by haydentherapper** [comment]
I'll start a separate issue about productionization, so we can chat more there about the current running production instance.

Do y'all have thoughts on the discussion on https://github.com/sigstore/fulcio/pull/280, about how best to implement a hybrid approach?
